# Generated by Django 6.0.2 on 2026-02-05 04:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('RESERVATION', 'Advance Reservation'), ('DRIVE_IN', 'Drive-In (Walk-up)')], default='DRIVE_IN', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Currently Parked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='PENDING', max_length=20)),
                ('ticket_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entry_time', models.DateTimeField(db_index=True)),
                ('expected_exit', models.DateTimeField(blank=True, null=True)),
                ('actual_exit', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_exit', models.DateTimeField()),
                ('new_exit', models.DateTimeField()),
                ('additional_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'booking_extensions',
                'ordering': ['-requested_at'],
            },
        ),
    ]
