# Generated by Django 6.0.2 on 2026-02-05 04:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('SUV', 'SUV'), ('TRUCK', 'Truck'), ('ELECTRIC_CAR', 'Electric Car'), ('ELECTRIC_SUV', 'Electric SUV'), ('BICYCLE', 'Bicycle'), ('VAN', 'Van'), ('BUS', 'Bus')], db_index=True, max_length=20)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin or through document upload')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='vehicles_user_id_c816b0_idx'), models.Index(fields=['plate_number', 'is_active'], name='vehicles_plate_n_839f63_idx'), models.Index(fields=['vehicle_type', 'is_active'], name='vehicles_vehicle_ce02a9_idx')],
                'unique_together': {('user', 'plate_number')},
            },
        ),
    ]
