# Generated by Django 6.0.2 on 2026-02-05 04:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Validity in days (null if entry-based)', null=True)),
                ('entry_count', models.PositiveIntegerField(blank=True, help_text='Number of entries allowed (null if time-based)', null=True)),
                ('max_duration_per_entry', models.PositiveIntegerField(blank=True, help_text='Max hours per single parking session', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='parking.facility')),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('entries_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to='pricing.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('strategy', models.CharField(choices=[('FLAT_RATE', 'Flat Rate (per entry)'), ('HOURLY', 'Hourly Rate'), ('SLAB', 'Slab-based (tiered)'), ('DYNAMIC', 'Dynamic (peak/off-peak)'), ('SUBSCRIPTION', 'Subscription/Pass')], default='HOURLY', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('applies_to_vehicle_types', models.JSONField(blank=True, default=list, help_text="Empty = all types. E.g., ['CAR', 'SUV']")),
                ('applies_to_spot_sizes', models.JSONField(blank=True, default=list, help_text="Empty = all sizes. E.g., ['MEDIUM', 'LARGE']")),
                ('priority', models.IntegerField(default=0)),
                ('free_minutes', models.PositiveIntegerField(default=0, help_text='First X minutes are free')),
                ('overstay_penalty_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='parking.facility')),
            ],
            options={
                'db_table': 'pricing_rules',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['facility', 'is_active', 'priority'], name='pricing_rul_facilit_30e9e0_idx'), models.Index(fields=['strategy', 'is_active'], name='pricing_rul_strateg_6f8154_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['facility', 'is_active'], name='subscriptio_facilit_c3007d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'is_active'], name='user_subscr_user_id_3e4873_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['subscription', 'is_active'], name='user_subscr_subscri_ba6116_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['expires_at'], name='user_subscr_expires_e42bda_idx'),
        ),
    ]
