# Generated by Django 6.0.2 on 2026-02-05 04:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('facility_type', models.CharField(choices=[('COMMERCIAL_LOT', 'Commercial Parking Lot'), ('MALL', 'Shopping Mall'), ('AIRPORT', 'Airport'), ('OFFICE_BUILDING', 'Office Building'), ('HOTEL', 'Hotel'), ('RESIDENTIAL', 'Residential'), ('PRIVATE_LOT', 'Private Lot'), ('STREET_PARKING', 'Street Parking')], default='COMMERCIAL_LOT', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='For map integration', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='For map integration', max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('has_ev_charging', models.BooleanField(default=False)),
                ('has_covered_parking', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=True)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_valet', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('total_spots', models.PositiveIntegerField(default=0)),
                ('available_spots', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'PARKING_OWNER'}, on_delete=django.db.models.deletion.PROTECT, related_name='owned_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_manage_bookings', models.BooleanField(default=True)),
                ('can_manage_violations', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='parking.facility')),
                ('staff_member', models.ForeignKey(limit_choices_to={'role': 'PARKING_STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='facility_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility_staff',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_covered', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(default=True, help_text='Accessibility for disabled persons')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('total_spots', models.PositiveIntegerField(default=0)),
                ('available_spots', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parking.facility')),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spot_number', models.CharField(max_length=20)),
                ('size', models.CharField(choices=[('SMALL', 'Small (Motorcycle/Bicycle)'), ('MEDIUM', 'Medium (Car)'), ('LARGE', 'Large (SUV/Van)'), ('XLARGE', 'Extra Large (Truck/Bus)')], db_index=True, default='MEDIUM', max_length=10)),
                ('has_ev_charger', models.BooleanField(db_index=True, default=False)),
                ('is_covered', models.BooleanField(default=False)),
                ('is_accessible', models.BooleanField(db_index=True, default=False, help_text='Handicap accessible')),
                ('is_vip', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under Maintenance'), ('DISABLED', 'Disabled')], db_index=True, default='AVAILABLE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_spot', to='bookings.booking')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.zone')),
            ],
            options={
                'db_table': 'parking_spots',
                'ordering': ['spot_number'],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['city', 'is_active'], name='facilities_city_87e03a_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['owner', 'is_active'], name='facilities_owner_i_9a6a40_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['slug'], name='facilities_slug_268922_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitystaff',
            index=models.Index(fields=['facility', 'is_active'], name='facility_st_facilit_0f5750_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitystaff',
            index=models.Index(fields=['staff_member', 'is_active'], name='facility_st_staff_m_30aef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facilitystaff',
            unique_together={('facility', 'staff_member')},
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['facility', 'is_active'], name='zones_facilit_6e135f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zone',
            unique_together={('facility', 'code')},
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['zone', 'status', 'is_active'], name='parking_spo_zone_id_5bb051_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['status', 'size', 'is_active'], name='parking_spo_status_8d996b_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['has_ev_charger', 'status'], name='parking_spo_has_ev__f45096_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parkingspot',
            unique_together={('zone', 'spot_number')},
        ),
    ]
