# Generated by Django 6.0.2 on 2026-02-05 04:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('parking', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('OVERSTAY', 'Overstay'), ('NO_TICKET', 'No Ticket/Unauthorized'), ('WRONG_SPOT', 'Wrong Spot'), ('BLOCKED_EXIT', 'Blocking Exit'), ('HANDICAP_VIOLATION', 'Handicap Spot Violation'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_evidence', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed'), ('DISPUTED', 'Under Dispute'), ('RESOLVED', 'Resolved'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=20)),
                ('violation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='bookings.booking')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='parking.facility')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'violations',
                'ordering': ['-violation_time'],
                'indexes': [models.Index(fields=['user', 'status'], name='violations_user_id_57f998_idx'), models.Index(fields=['facility', 'status'], name='violations_facilit_1b4087_idx'), models.Index(fields=['violation_type', 'status'], name='violations_violati_2bd05c_idx')],
            },
        ),
    ]
